spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.ysrtuoccvlsdiwkdwwsz}
    password: ${SPRING_DATASOURCE_PASSWORD:Sublens0223}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
jwt:
  secret: 0d5ad301f9af1047ba94371c2f281da7d93ab508c55de822834deae2892fb1b6
  access-token-expiration: 3600000 # 1시간
  refresh-token-expiration: 86400000 # 24시간
resend:
  api:
    key: ${RESEND_API_KEY:re_EF3JmSXy_KbxEjomRa49ayDDrC2Ed9iB9}
